### ISSUE TITLE
champs de bataille

### ISSUE THREAD

**Issue by Trotropic** [Trotropic/ArkadiaServeur#17]
En champs de bataille (tout les bg) quand on tue un ennemie de la faction adverse cela fait crash le serveur.

**Comment by nadeauk6012** [comment]
Surement du au .deb bg, le seul soucis on pourra seulement test quand je vais arrivé avec ma clique :P

**Comment by nadeauk6012** [comment]
j'ai fait le test avec un de mes personnages allianceux et j'ai pas eu de problème de crash serveur.
