### ISSUE TITLE
Bug d'affichage ou quête indisponible/bugué ? 

### ISSUE THREAD

**Issue by romzer44** [Trotropic/ArkadiaServeur#38]
Nom de la quête : Une lettre écarlate

![image](https://user-images.githubusercontent.com/63554624/79243993-a8b69480-7e76-11ea-852d-ee19c93a4e77.png)

**Comment by nadeauk6012** [comment]
Quêtes lootable via les Guerrier écarlate(16%) et validé au près du Garde noir Simmer près de Gordo dans la petite maison.

https://fr.classic.wowhead.com/npc=1519/garde-noir-simmer

**Comment by romzer44** [comment]
D’accord autant pour moi merci

Le mer. 15 avr. 2020 à 03:31, nadeauk6012 <notifications@github.com> a
écrit :

**Comment by nadeauk6012** [comment]
Fait plaisir :)
