### ISSUE TITLE
Tour des mages (axe)

### ISSUE THREAD

**Issue by Trotropic** [Trotropic/ArkadiaServeur#42]
Tout ce qui est lié à la tour des mages ne fonctionne pas.
 Table inclinable

**Comment by nadeauk6012** [comment]
Il n'y a pas de table il faut seulement récolté les ressources demandé ensuite parler a ce pnj.
![Annotation 2020-04-14 211513](https://user-images.githubusercontent.com/26035422/79288554-0ce85100-7e95-11ea-9995-39d742e9686f.png)
