### ISSUE TITLE
tp shattra à newdalaran hs

### ISSUE THREAD

**Issue by Cerfbois** [Trotropic/ArkadiaServeur#51]
impossible de cliquer sur le portail
![WoWScrnShot_041520_171317](https://user-images.githubusercontent.com/63495462/79354401-a61e7280-7f3c-11ea-8675-c996944eaa0c.jpg)

**Comment by nadeauk6012** [comment]
Fix :) au prochain redémarrage les portails vers shattrah seront séparer un d'un côté et le second de l'autre côté de celui-ci :)
